import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Bodyhome from './Components/Bodyhome/index'
import Portfolio from './Portfolio/index'
import Team from './Components/Team/index'
import Testimonials from './Components/Testimonials/index'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <Bodyhome/>
      <Team/>
    <Testimonials/>
    </div>
  )
}
